Repository f-lab-edu/ottsharing, pull requests merged in 2022-03, with the labels that each got.

#72 feat: User Entity&Repository 개선
  src/main/java/kr/flab/ottsharing/entity/User.java
  src/main/java/kr/flab/ottsharing/repository/UserRepository.java
  src/test/java/kr/flab/ottsharing/repository/UserRepositoryTest.java
Labels: enhancement, refactoring

#79 #refactor useRepository
  src/main/java/kr/flab/ottsharing/repository/UserRepository.java
Labels: bug, refactoring

#81 feat: MoneyRepository
  src/main/java/kr/flab/ottsharing/repository/MoneyRepository.java
Labels: enhancement

#83 Party - Entity & Repository 개선 #31
  src/main/java/kr/flab/ottsharing/entity/Party.java
  src/main/java/kr/flab/ottsharing/repository/PartyRepository.java
  src/main/java/kr/flab/ottsharing/service/LoginService.java
  src/main/java/kr/flab/ottsharing/service/MyPartyService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
  src/main/java/kr/flab/ottsharing/service/PartyWaitingService.java
  src/test/java/kr/flab/ottsharing/repository/PartyMemberTest.java
  src/test/java/kr/flab/ottsharing/repository/PartyRepositoryTest.java
  src/test/java/kr/flab/ottsharing/repository/UserRepositoryTest.java
Labels: refactoring

#84 PartyMember - Entity & Repository 개선 #32
  src/main/java/kr/flab/ottsharing/entity/PartyMember.java
  src/main/java/kr/flab/ottsharing/repository/PartyMemberRepository.java
  src/test/java/kr/flab/ottsharing/repository/PartyMemberRepositoryTest.java
  src/test/java/kr/flab/ottsharing/repository/PartyMemberTest.java
Labels: refactoring

#85 PartyWating - Entity & Repository 개선 #33
  src/main/java/kr/flab/ottsharing/entity/PartyWaiting.java
  src/main/java/kr/flab/ottsharing/repository/PartyWaitingRepository.java
  src/main/java/kr/flab/ottsharing/service/LoginService.java
  src/main/java/kr/flab/ottsharing/service/MyPartyService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
  src/main/java/kr/flab/ottsharing/service/PartyWaitingService.java
  src/test/java/kr/flab/ottsharing/repository/PartyWaitingRepositoryTest.java
Labels: enhancement, refactoring

#90 LoginService, LoginController -> UserService, UserController 이름 변경 #89
  src/main/java/kr/flab/ottsharing/controller/UserController.java
  src/main/java/kr/flab/ottsharing/service/UserService.java
Labels: refactoring

#82 #39 #45 UserService,UserController
  src/main/java/kr/flab/ottsharing/controller/UserController.java
  src/main/java/kr/flab/ottsharing/protocol/MyPageUpdateResult.java
  src/main/java/kr/flab/ottsharing/service/UserService.java
Labels: enhancement

#91 UserService - fetchMyInfo #38
  src/main/java/kr/flab/ottsharing/protocol/MyInfo.java
  src/main/java/kr/flab/ottsharing/service/UserService.java
Labels: enhancement

#92 UserController - GET /myPage #44
  src/main/java/kr/flab/ottsharing/controller/UserController.java
Labels: enhancement

#93 UserService - deleteMyInfo #40
  src/main/java/kr/flab/ottsharing/protocol/UserDeleteResult.java
  src/main/java/kr/flab/ottsharing/service/UserService.java
Labels: enhancement

#94 UserController - DELETE /myPage #46
  src/main/java/kr/flab/ottsharing/controller/UserController.java
Labels: enhancement

#98 develop 브랜치의 컴파일 에러, 테스트 실패 모두 해결하기 #97
  .gitignore
  build.gradle
  src/main/java/kr/flab/ottsharing/controller/UserController.java
  src/main/java/kr/flab/ottsharing/service/PartyWaitingService.java
  src/main/resources/application.yml
Labels: bug

#87 UserController - POST /register #43
  src/main/java/kr/flab/ottsharing/controller/UserController.java
  src/main/java/kr/flab/ottsharing/protocol/RegisterResult.java
  src/main/java/kr/flab/ottsharing/service/UserService.java
  src/test/java/kr/flab/ottsharing/service/UserServiceTest.java
Labels: enhancement, refactoring

#101 Service & Controller - POST /party/create #47 #51
  src/main/java/kr/flab/ottsharing/controller/PartyController.java
  src/main/java/kr/flab/ottsharing/protocol/PartyCreateResult.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
Labels: enhancement, refactoring
