Repository f-lab-edu/ottsharing, pull requests merged in 2022-04, with the labels that each got.

#103 refactor : 경고제거
  .gitignore
  src/main/java/kr/flab/ottsharing/controller/PartyController.java
  src/main/java/kr/flab/ottsharing/controller/UserController.java
  src/main/java/kr/flab/ottsharing/entity/Party.java
  src/main/java/kr/flab/ottsharing/entity/User.java
  src/main/java/kr/flab/ottsharing/repository/PartyWaitingRepository.java
  src/main/java/kr/flab/ottsharing/repository/UserRepository.java
  src/main/java/kr/flab/ottsharing/service/MyPartyService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
  src/main/java/kr/flab/ottsharing/service/PartyWaitingService.java
  src/main/java/kr/flab/ottsharing/service/UserService.java
  src/test/java/kr/flab/ottsharing/repository/PartyRepositoryTest.java
  src/test/java/kr/flab/ottsharing/repository/PartyWaitingRepositoryTest.java
Labels: bug

#109 feat: 파티 해체 및 리더확인 기능 구현
  src/main/java/kr/flab/ottsharing/controller/PartyController.java
  src/main/java/kr/flab/ottsharing/repository/PartyMemberRepository.java
  src/main/java/kr/flab/ottsharing/repository/PartyRepository.java
  src/main/java/kr/flab/ottsharing/repository/UserRepository.java
  src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
  src/main/java/kr/flab/ottsharing/service/UserService.java
  src/main/java/kr/flag/ottsharing/exception/WrongInfoException.java
  src/main/resources/application.yml
  src/test/java/kr/flab/ottsharing/repository/UserRepositoryTest.java
Labels: enhancement

#113 feat : 파티 탈퇴 api 구현
  src/main/java/kr/flab/ottsharing/controller/PartyController.java
  src/main/java/kr/flab/ottsharing/repository/PartyMemberRepository.java
  src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
Labels: enhancement

#121 feat: GET /myParty 컨트롤러와 서비스 구현
  src/main/java/kr/flab/ottsharing/controller/MyPartyController.java
  src/main/java/kr/flab/ottsharing/controller/PartyController.java
  src/main/java/kr/flab/ottsharing/protocol/MyParty.java
  src/main/java/kr/flab/ottsharing/protocol/PartyMemberInfo.java
  src/main/java/kr/flab/ottsharing/service/MyPartyService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
Labels: enhancement

#119 feat: PartyWaitingService addWaiting 대기자 등록 구현
  src/main/java/kr/flab/ottsharing/controller/PartyController.java
  src/main/java/kr/flab/ottsharing/service/PartyWaitingService.java
Labels: enhancement

#118 feat: MoneyService settle 구현
  src/main/java/kr/flab/ottsharing/service/MoneyService.java
Labels: enhancement

#120 feat: DELETE /waiting 컨트롤러와 서비스 구현
  src/main/java/kr/flab/ottsharing/controller/PartyWaitingController.java
  src/main/java/kr/flab/ottsharing/protocol/DeleteWaitingResult.java
  src/main/java/kr/flab/ottsharing/service/PartyWaitingService.java
Labels: enhancement

#122 feat : 파티정보 수정 api 기능 구현
  build.gradle
  src/main/java/kr/flab/ottsharing/controller/PartyController.java
  src/main/java/kr/flab/ottsharing/entity/PartyMember.java
  src/main/java/kr/flab/ottsharing/protocol/UpdatePartyInfo.java
  src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
Labels: enhancement

#124 feat : 충전 api 기능 구현
  src/main/java/kr/flab/ottsharing/controller/MoneyController.java
  src/main/java/kr/flab/ottsharing/service/MoneyService.java
Labels: enhancement

#125 feat : 출금 api 구현
  src/main/java/kr/flab/ottsharing/controller/MoneyController.java
  src/main/java/kr/flab/ottsharing/exception/MoneyException.java
  src/main/java/kr/flab/ottsharing/service/MoneyService.java
Labels: enhancement

#123 POST /party/join 서비스 및 컨트롤러 구현
  src/main/java/kr/flab/ottsharing/controller/PartyController.java
  src/main/java/kr/flab/ottsharing/protocol/PartyJoinResult.java
  src/main/java/kr/flab/ottsharing/service/MoneyService.java
  src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
  src/main/resources/META-INF/spring-configuration-metadata.json
  src/main/resources/application.yml
Labels: enhancement

#127 모든 컨트롤러와, 컨트롤러와 관련된 서비스에 대해 쿠키로그인 적용
  src/main/java/kr/flab/ottsharing/controller/MoneyController.java
  src/main/java/kr/flab/ottsharing/controller/PartyController.java
  src/main/java/kr/flab/ottsharing/controller/PartyWaitingController.java
  src/main/java/kr/flab/ottsharing/controller/UserController.java
  src/main/java/kr/flab/ottsharing/protocol/UpdatePartyInfo.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
  src/main/java/kr/flab/ottsharing/service/PartyWaitingService.java
  src/main/java/kr/flab/ottsharing/service/UserService.java
Labels: refactoring

#132 feat : 환불 Service 구현
  src/main/java/kr/flab/ottsharing/protocol/RefundResult.java
  src/main/java/kr/flab/ottsharing/service/MoneyService.java
Labels: enhancement

#134 PartyService - createParty 빠진 부분들 구현
  src/main/java/kr/flab/ottsharing/protocol/PartyCreateResult.java
  src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
  src/main/java/kr/flab/ottsharing/service/PartyWaitingService.java
Labels: enhancement

#135 feat: join할때 4명 꽉차면 isFull=True
  src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
Labels: enhancement

#136 정산 및 자동결제 스케줄러
  src/main/java/kr/flab/ottsharing/OttsharingApplication.java
  src/main/java/kr/flab/ottsharing/repository/PartyMemberRepository.java
  src/main/java/kr/flab/ottsharing/scheduler/PaySettleScheduler.java
  src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
Labels: enhancement

#142 PartyService - deleteParty 파티원들 모두 환불받도록 구현
  src/main/java/kr/flab/ottsharing/controller/PartyController.java
  src/main/java/kr/flab/ottsharing/protocol/PartyDeleteResult.java
  src/main/java/kr/flab/ottsharing/service/MoneyService.java
  src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
Labels: enhancement

#148 feat : partyId를 API 호출당시 받아오기(UpdatePartyInfo)와 받아온 파티id에 속하는지 확인 작업 삭제
  src/main/java/kr/flab/ottsharing/protocol/UpdatePartyInfo.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
Labels: bug

#149 fix : 전역변수 serviceFee가 아닌 지역변수 payMoney를 통해 값 계산하도록 수정
  src/main/java/kr/flab/ottsharing/service/MoneyService.java
Labels: bug

#147 대기자 목록 삭제 제대로 되게끔 수정
  src/main/java/kr/flab/ottsharing/repository/PartyWaitingRepository.java
  src/main/java/kr/flab/ottsharing/service/PartyWaitingService.java
  src/test/java/kr/flab/ottsharing/repository/PartyWaitingRepositoryTest.java
Labels: bug

#158 feat : 두번 환불이 되지 않기 위한 처리, filterRefundDate, checkDiscount & refator
  src/main/java/kr/flab/ottsharing/service/MoneyService.java
Labels: enhancement, refactoring

#165 main에 있던 README develop에 추가
  README.md
Labels: documentation

#164 수민님 UpdatePartyInfo 코드 옮겨오기
  src/main/java/kr/flab/ottsharing/controller/UserController.java
  src/main/java/kr/flab/ottsharing/dto/request/PartyUpdateDto.java
  src/main/java/kr/flab/ottsharing/dto/response/MyInfo.java
  src/main/java/kr/flab/ottsharing/dto/response/PartyMemberInfo.java
  src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
  src/main/java/kr/flab/ottsharing/service/UserService.java
  src/test/java/kr/flab/ottsharing/service/UserServiceTest.java
Labels: refactoring

#162 공용 헤더 추가 및 적용
  src/main/java/kr/flab/ottsharing/controller/MoneyController.java
  src/main/java/kr/flab/ottsharing/controller/PartyController.java
  src/main/java/kr/flab/ottsharing/controller/PartyWaitingController.java
  src/main/java/kr/flab/ottsharing/controller/UserController.java
  src/main/java/kr/flab/ottsharing/dto/request/PartyUpdateDto.java
  src/main/java/kr/flab/ottsharing/dto/response/DeleteWaitingResult.java
  src/main/java/kr/flab/ottsharing/dto/response/MyInfo.java
  src/main/java/kr/flab/ottsharing/dto/response/MyPageUpdateResult.java
  src/main/java/kr/flab/ottsharing/dto/response/MyParty.java
  src/main/java/kr/flab/ottsharing/dto/response/PartyCreateResult.java
  src/main/java/kr/flab/ottsharing/dto/response/PartyDeleteResult.java
  src/main/java/kr/flab/ottsharing/dto/response/PartyJoinResult.java
  src/main/java/kr/flab/ottsharing/dto/response/PartyMemberInfo.java
  src/main/java/kr/flab/ottsharing/dto/response/PayResult.java
  src/main/java/kr/flab/ottsharing/dto/response/RefundResult.java
  src/main/java/kr/flab/ottsharing/dto/response/RegisterResult.java
  src/main/java/kr/flab/ottsharing/dto/response/UserDeleteResult.java
  src/main/java/kr/flab/ottsharing/dto/response/common/CommonResponse.java
  src/main/java/kr/flab/ottsharing/dto/response/common/ResultCode.java
  src/main/java/kr/flab/ottsharing/exception/MoneyException.java
  src/main/java/kr/flab/ottsharing/exception/WrongInfoException.java
  src/main/java/kr/flab/ottsharing/scheduler/PaySettleScheduler.java
  src/main/java/kr/flab/ottsharing/service/MoneyService.java
  src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
  src/main/java/kr/flab/ottsharing/service/PartyWaitingService.java
  src/main/java/kr/flab/ottsharing/service/UserService.java
  src/test/java/kr/flab/ottsharing/service/UserServiceTest.java
Labels: refactoring

#161 POST에서 RequestBody를 오브젝트로 맵핑해서, 스웨거에서 드러나게 하기
  src/main/java/kr/flab/ottsharing/controller/MoneyController.java
  src/main/java/kr/flab/ottsharing/controller/PartyController.java
  src/main/java/kr/flab/ottsharing/controller/PartyWaitingController.java
  src/main/java/kr/flab/ottsharing/controller/UserController.java
  src/main/java/kr/flab/ottsharing/dto/request/LoginDto.java
  src/main/java/kr/flab/ottsharing/dto/request/MoneyDto.java
  src/main/java/kr/flab/ottsharing/dto/request/PartyCreateDto.java
  src/main/java/kr/flab/ottsharing/dto/request/PartyIdDto.java
  src/main/java/kr/flab/ottsharing/dto/request/PartyUpdateDto.java
  src/main/java/kr/flab/ottsharing/dto/request/RegisterDto.java
  src/main/java/kr/flab/ottsharing/dto/request/UserUpdateDto.java
  src/main/java/kr/flab/ottsharing/dto/response/MyInfo.java
  src/main/java/kr/flab/ottsharing/dto/response/MyParty.java
  src/main/java/kr/flab/ottsharing/dto/response/PartyMemberInfo.java
  src/main/java/kr/flab/ottsharing/dto/response/RefundResult.java
  src/main/java/kr/flab/ottsharing/dto/response/common/CommonResponse.java
  src/main/java/kr/flab/ottsharing/dto/response/common/ResultCode.java
  src/main/java/kr/flab/ottsharing/exception/MoneyException.java
  src/main/java/kr/flab/ottsharing/exception/WrongInfoException.java
  src/main/java/kr/flab/ottsharing/protocol/DeleteWaitingResult.java
  src/main/java/kr/flab/ottsharing/protocol/MyInfo.java
  src/main/java/kr/flab/ottsharing/protocol/MyPageUpdateResult.java
  src/main/java/kr/flab/ottsharing/protocol/PartyCreateResult.java
  src/main/java/kr/flab/ottsharing/protocol/PartyDeleteResult.java
  src/main/java/kr/flab/ottsharing/protocol/PartyJoinResult.java
  src/main/java/kr/flab/ottsharing/protocol/PartyMemberInfo.java
  src/main/java/kr/flab/ottsharing/protocol/PayResult.java
  src/main/java/kr/flab/ottsharing/protocol/RefundResult.java
  src/main/java/kr/flab/ottsharing/protocol/RegisterResult.java
  src/main/java/kr/flab/ottsharing/protocol/UpdatePartyInfo.java
  src/main/java/kr/flab/ottsharing/protocol/UserDeleteResult.java
  src/main/java/kr/flab/ottsharing/scheduler/PaySettleScheduler.java
  src/main/java/kr/flab/ottsharing/service/MoneyService.java
  src/main/java/kr/flab/ottsharing/service/PartyMemberService.java
  src/main/java/kr/flab/ottsharing/service/PartyService.java
  src/main/java/kr/flab/ottsharing/service/PartyWaitingService.java
  src/main/java/kr/flab/ottsharing/service/UserService.java
  src/test/java/kr/flab/ottsharing/service/UserServiceTest.java
Labels: refactoring
